### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by cfoellmann** [black-studio/black-studio-tinymce-widget#31]
Following PHP notice (VVV; php 5.5.x):
```
Notice
Trying to get property of non-object	

1

wp-includes/class-wp-editor.php:1255

_WP_Editors::wp_fullscreen_html()
_WP_Editors::editor_js()
do_action('admin_print_footer_scripts')

Core
```
@marcochiesi you should have a look at https://wordpress.org/plugins/query-monitor/

**Comment by marcochiesi** [comment]
This issue was [fixed](https://core.trac.wordpress.org/ticket/30071) in WordPress core, so it can be closed.
