### ISSUE TITLE
Visual Editor in Page Builder

### ISSUE THREAD

**Issue by gregpriday** [black-studio/black-studio-tinymce-widget#34]
Hi Marco

I've just started testing Page Builder in WordPress 4.2. Something I noticed is that the Visual Editor widget no longer works properly. It triggers the following error:

`Uncaught TypeError: Cannot read property 'canvas' of undefined`

It works properly in the widget area. I'm busy investigating, I'll submit a PR if I can figure this out (maybe it's something in Page Builder itself). Hopefully you can take a quick look though.

**Comment by gregpriday** [comment]
Never mind, I think I spoke too soon.

Issue is that I was using a development download of Page Builder in the folder siteorigin-panels-develop. The folder name meant the Visual Editor wasn't loading the compatibility code. My bad!

**Comment by sagive** [comment]
hey @gregpriday 
i would love to hear how you solved this.
i took a look at the code and found the compatibility function but nothing stood up...

Is their a problem changing the page builder folder name? something else?
would really apreaciate your input ;)
