### ISSUE TITLE
Black studio doesn't work on Customizer

### ISSUE THREAD

**Issue by pixedelic** [black-studio/black-studio-tinymce-widget#36]
Hi, and thanks for the great plugin.

The Visual Editor doesn't seem to work fine on customize.php page. The Text tab works only... if I try to type something on the Visual tab I only see the blank panel. 

Side effect: I'm developing a theme to sell or distribute. The theme comes with tinyMCE fields among the other Customizer option, but activating Black Studio generates some javascript errors. So, without your plugin installed, my editors work fine, they stop working when I activate BlackStudio

Any advice, at least for the first point? Thank you in advance. Gran bel plugin, ovviamente, complimenti.

Manuel :-)

**Comment by marcochiesi** [comment]
Hi Manuel,
thank you for your message. We just released a new version of the plugin (2.2.4) which should fix the issue related to the theme customizer.
Please check it out and post a follow-up if you're still experiencing issues with your theme. We want to ensure maximum compatibility with other plugins and themes.

**Comment by pixedelic** [comment]
Great, thank you, just tested and the visual editor works fine... but drop-down fields can't be open (tested with TwentyFifteen and no plugins but yours):

![screen shot 2015 05 14 at 17 00 45](https://cloud.githubusercontent.com/assets/527057/7634399/ef8fb30a-fa5a-11e4-85b2-5e1352fe04a7.png)

However great improvement, keep up the great work. I'll manage to make work my editor areas as well... somehow :-)

**Comment by marcochiesi** [comment]
Thanks for pointing out that. The styles dropdown not appearing is a z-index issue, it has been fixed on the dev branch (38859f754714687a26ddec5c71b2113a6edb67c4) and it will be included in the next public release. In the meantime I noticed another problem occurring only in Customizer: the editor buttons added by WP core (i.e. links, text colors, symbols) are not displayed.

**Comment by marcochiesi** [comment]
The latest version 2.2.8 has fixed all pending issues within Customizer, so I am going to close this topic.
