### ISSUE TITLE
After update to 2.2.7: Better Font Awesome button problem

### ISSUE THREAD

**Issue by EJOweb** [black-studio/black-studio-tinymce-widget#39]
The [Better Font Awesome] (https://github.com/MickeyKay/better-font-awesome) button stopped working from the moment I updated the Black Studio Tinymce Widget plugin from 2.2.6 to 2.2.7.

I love your plugin by the way!

**Comment by marcochiesi** [comment]
The cause of this is not in a Black Studio Tinymce Widget plugin, but in a Better Font Awesome update (in particular from 1.3.4 to 1.3.5).

The affected code is at the beginning of file better-font-awesome/lib/better-font-awesome-library/js/admin.js, where the line:
`$( '.bfa-iconpicker' ).not( '.initialized' )`
became
`$( '.bfa-iconpicker:visible' ).not( '.initialized' )`

@MickeyKay could you assist on this?

**Comment by MickeyKay** [comment]
Great catch you two. Thanks for the heads up, and @marcochiesi especially, thanks for tracking this one down. Will give you both a props in the changelog.

I actually don't think that `:visible` was meant to ever get in there. Looks like I forgot to run the final `grunt build` on that last release. Again, thanks a ton!

**Comment by MickeyKay** [comment]
Alrighty, just relesed v1.4.0 which should fix this issue. Thanks again! Add props to the readme but looks like the cache hasn't cleared yet.

**Comment by EJOweb** [comment]
Thank you both!
