### ISSUE TITLE
Conflict with Site Origin Page Builder breaks WP-Admin in some situations

### ISSUE THREAD

**Issue by jbeales** [black-studio/black-studio-tinymce-widget#44]
When both TinyMCE Widget and the Site Origin Page Builder plugin are installed, using WordPress 5 or greater and the block editor, (Gutenberg), when editing a non-page-builder page something happens that breaks a lot of the WP-Admin UI. Most icons in the admin bar and left-hand menu turn into boxes, alignment goes off in the left-hand menu, and any Classic blocks in the editor lose much of their TinyMCE functionality. See also [this WordPress forum thread](https://wordpress.org/support/topic/missing-dashicons-when-used-with-siteorigin-page-builder-and-block-editor/)

Steps to reproduce:

- Install & Activate both Black Studio TinyMCE Widget and Site Origin Page Builder plugins.
- Open a page to edit. If it's a Page Builder page turn it into a non-Page-Builder page.
- Notice the icons missing from the admin bar. 
- Add a "Classic" block and try to add a link using TinyMCE, (nothing will happen when clicking the link button).

**Comment by marcochiesi** [comment]
Thanks for the report.
Fixed on ac060f0f058ef3c820e46bccdb92728a5d11cf35
