### ISSUE TITLE
2.6.5: Cannot save Block Editor when SiteOrigin Page Builder & Black Studio TinyMCE Widget active

### ISSUE THREAD

**Issue by AlexGStapleton** [black-studio/black-studio-tinymce-widget#45]
[Reported here](https://siteorigin.com/thread/pagebuilder-preventing-wordpress-block-editor-from-saving/)

When SiteOrigin Page Builder and Black Studio TinyMCE Widget are active, users can't save the block editor. Rolling back to 2.6.4 prevents this issue so a change made in 2.6.5 must have caused this issue.

**Comment by marcochiesi** [comment]
Thanks for the report. I will look into this as soon as possible.

**Comment by Misplon** [comment]
Thanks Marco :)

**Comment by marcochiesi** [comment]
The changes made in v2.6.5 were reverted and an alternative fix was added in v.2.6.6, just released.
@AlexGStapleton and @Misplon please could you check if this fixes the issue you reported? Thanks!

**Comment by AlexGStapleton** [comment]
I can't replicate this issue anymore. 👍

**Comment by Misplon** [comment]
Awesome :) Thanks.
